# Generated by Django 4.1 on 2022-08-11 16:30

from django.db import migrations
import imagekit.models.fields
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(upload_to=shop.models.RandomFileName('header_carousel')),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(upload_to=shop.models.RandomFileName('products')),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(upload_to=shop.models.RandomFileName('products')),
        ),
    ]
