# Generated by Django 4.1 on 2022-08-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_header_thumbnail_alter_product_thumbnail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='О нас')),
            ],
            options={
                'verbose_name': 'Страница "О нас"',
                'verbose_name_plural': 'Страница "О нас"',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping', models.TextField(verbose_name='Доставка товара')),
                ('payment', models.TextField(verbose_name='Оплата')),
                ('refund', models.TextField(verbose_name='Условия возврата')),
                ('qa', models.TextField(verbose_name='Вопросы и ответы')),
            ],
            options={
                'verbose_name': 'Страница "Помощь"',
                'verbose_name_plural': 'Страница "Помощь"',
            },
        ),
    ]
