# Generated by Django 4.1 on 2022-08-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_about_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='refund',
        ),
        migrations.AddField(
            model_name='info',
            name='service',
            field=models.TextField(blank=True, null=True, verbose_name='Уход'),
        ),
        migrations.AlterField(
            model_name='info',
            name='payment',
            field=models.TextField(blank=True, null=True, verbose_name='Оплата'),
        ),
        migrations.AlterField(
            model_name='info',
            name='qa',
            field=models.TextField(blank=True, null=True, verbose_name='Вопросы и ответы'),
        ),
        migrations.AlterField(
            model_name='info',
            name='shipping',
            field=models.TextField(blank=True, null=True, verbose_name='Доставка товара'),
        ),
    ]
